apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: xmelisek-ambulance-ufe
spec:
  module-uri: http://xmelisek-ambulance-ufe.wac-hospital/build/heos-ufe.esm.js
                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: xmelisek-ambulance-order-list    # element, ktorý bude vložený na stránku
                                    # pri navigácii na zoznam čakajúcich
      path: xmelisek-ambulance-heos      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: MelisekM - Hospital equipment order system    # názov mikro aplikácie
      details: Spravuje objednavky noveho vybavenia pre nemocnice
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha1             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach